version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_MAIN_USER}
      POSTGRES_PASSWORD: ${DB_MAIN_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB_DEV: ${DB_NAME_DEVELOPMENT}
      POSTGRES_DB_TEST: ${DB_NAME_TEST}
    volumes:
      - ./.docker/services/db/data:/var/lib/postgresql/data
      - ./.docker/services/db/volume:/docker-entrypoint-initdb.d
    restart: always

  minio:
    image: quay.io/minio/minio
    volumes:
      - ./.docker/services/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    restart: always

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./.docker/services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/services/nginx/ssl:/etc/ssl
    depends_on:
      - app